<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Relic.Framework\Relic.Framework.csproj" />
    <ProjectReference Include="..\Relic.Content\Relic.Content.csproj" />
  </ItemGroup>

</Project>
