// This file is part of the Prowl Game Engine
// Licensed under the MIT License. See the LICENSE file in the project root for details.
//
// Marker for every GameObject generated from a .map import, so an automatic
// hot-reload (TrenchBroom save -> reimport) can remove exactly what it created
// without touching anything the user placed by hand.

namespace Prowl.Runtime.Relic;

/// <summary>
/// Tags a GameObject as generated by <see cref="RelicSceneBuilder"/>.
/// Hot-reload clears objects carrying this marker, then rebuilds from the .map.
/// </summary>
public sealed class RelicMapGenerated : MonoBehaviour
{
    /// <summary>Absolute .map path this object was built from (may be empty for legacy objects).</summary>
    public string SourceMapPath = string.Empty;
}
